[colors.bright]
black = (color0)
red = (color1)
green = (color2)
yellow = (color3)
blue = (color4)
magenta = (color5)
cyan = (color6)
white = (color7)

[colors.normal]
black = (color0)
red = (color1)
green = (color2)
yellow = (color3)
blue = (color4)
magenta = (color5)
cyan = (color6)
white = (color7)

[colors.primary]
background = (color0)
foreground = (color15)

[font]
size = 12

[font.bold]
family = "Terminess Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "Terminess Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "Terminess Nerd Font Propo"
style = "Italic"

[font.normal]
family = "Terminess Nerd Font Propo"
style = "Regular"

[window.padding]
x = 0
y = 0
