[colors.bright]
black = "#271c16"
red = "#c79171"
green = "#c78838"
yellow = "#354db6"
blue = "#6e6dc3"
magenta = "#9885c5"
cyan = "#c290b1"
white = "#c9c6c4"

[colors.normal]
black = "#271c16"
red = "#c79171"
green = "#c78838"
yellow = "#354db6"
blue = "#6e6dc3"
magenta = "#9885c5"
cyan = "#c290b1"
white = "#c9c6c4"

[colors.primary]
background = "#271c16"
foreground = "#c9c6c4"

[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window.padding]
x = 2
y = 2