[colors.normal]
black   = "#243237"
red     = "#C86663"
green   = "#C8A374"
yellow  = "#67ADC7"
blue    = "#5095C8"
magenta = "#417BC8"
cyan    = "#C2B1B2"
white   = "#F0FEFF"

[colors.bright]
black   = "#38464B"
red     = "#DC7A77"
green   = "#DCB788"
yellow  = "#7BC1DB"
blue    = "#64A9DC"
magenta = "#558FDC"
cyan    = "#D6C5C6"
white   = "#FFFFFF"

[colors.primary]
background = "#1A282D"
foreground = "#EBF9FE"

[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window.padding]
x = 4
y = 4

[window]
decorations = "None"
