[colors.bright]
black = "#0e0706"
red = "#3630D6"
green = "#D54FBC"
yellow = "#ED01FD"
blue = "#E121ED"
magenta = "#FE859D"
cyan = "#F791AA"
white = "#f4cde0"

[colors.normal]
black = "#0e0706"
red = "#3630D6"
green = "#D54FBC"
yellow = "#ED01FD"
blue = "#E121ED"
magenta = "#FE859D"
cyan = "#F791AA"
white = "#f4cde0"

[colors.primary]
background = "#0e0706"
foreground = "#f4cde0"

[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window.padding]
x = 0
y = 0
